name: Auto Deploy Databricks Pipeline

on:
  push:
    paths:
      - 'ahd-data-pipelines/conf.j2/**' # Watch for changes in any file under ahd-data-pipelines/conf.j2 directory

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Databricks CLI
        uses: databrickslabs/databricks-terraform@main
        with:
          cmd: init
          token: ${{ secrets.DATABRICKS_TOKEN_DEV }}
          url: ${{ secrets.DATABRICKS_URL_DEV }}
      
      - name: Determine changes and deploy pipelines
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^ahd-data-pipelines/conf\.j2/parameters/census/language/'; then
            echo "Updating Language Pipeline"
          fi
