name: pytest coverage test

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install modules
        run: |
          pip install arcgis==2.2.0
          pip install pytz==2023.3.post1
          pip install pyyaml==6.0.1
          pip install shapely==2.0.2
          pip install geopandas==0.14.2
          pip install numpy==1.26.3
          pip install geopy==2.4.1
          pip install boto3==1.34.27
          pip install openpyxl==3.1.2
          pip install dlt==0.4.2
          pip install sqlalchemy==2.0.25
          pip install psycopg2-binary==2.9.9
          pip install yamllint==^1.35.1

      - name: Run pytest coverage check
        #run: pytest --cov=src --cov-fail-under=30.00



