name: pytest coverage test

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Initialize Poetry
        run: |
          poetry init -n

      - name: Set up virtual environment and install dependencies
        run: |
          poetry install

      # - name: Create Coverage Config File
      #   run: |
      #     echo "[run]" > /home/runner/.coveragerc
      #     echo "omit = src/ahd_data_pipelines/common/ArcGIS/OverwriteFS/OverwriteFS.py " >> /home/runner/.coveragerc
      #     echo "       src/ahd_data_pipelines/tasks/esri/green_data_update.py" >> /home/runner/.coveragerc
      #     echo "       src/ahd_data_pipelines/tasks/esri/green_data_update_job.py" >> /home/runner/.coveragerc

      - name: Run pytest coverage check
        run: pytest --cov=src --cov-fail-under=30.00



