name: Flake8 Lint

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install modules
        run: pip install flake8

      - name: Run Flake8
        run: flake8 --ignore=E501



