name: Validate DEV deployment config

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Running Validate on dev
        run: |
          echo "Validate the dev configuration"
          python --version

