name: Update Version

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

    # Check GitHub API for newest tag of check_rancher2 
      - name: ahd-data-pipelines - Check for newest available version
        uri:
          url: https://api.github.com/repos/ontargetcomputing/ahd-data-pipelines/tags
          method: GET
          return_content: yes
          status_code: 200
          body_format: json
        register: result

      # Debug output for the full result variable
      - debug:
          msg: "{{ result }}"
        ignore_errors: True

      # Debug output to see the latest tag. This should show an output like: 1.12.0
      - debug:
          msg: "{{ result.json[0].name }}"
        ignore_errors: True

      - name: Determine Semantic Version Label
        id: determine_label
        run: |
          latest_tag=$(<latest_tag.txt)
          current_version=$(echo $latest_tag | cut -d 'v' -f 2)
          IFS='.' read -r major minor patch <<< "$current_version"
          if [ $major -eq 0 ]; then
            label="major"
          elif [ $minor -eq 0 ]; then
            label="minor"
          else
            label="patch"
          fi
          echo "Label: $label"

      - name: Increase version number
        id: increase_version
        run: |
          latest_tag=$(<latest_tag.txt)
          current_version=$(echo $latest_tag | cut -d 'v' -f 2)
          IFS='.' read -r major minor patch <<< "$current_version"
          case $label in
            major)
              new_version="$((major + 1)).0.0"
              ;;
            minor)
              new_version="$major.$((minor + 1)).0"
              ;;
            patch)
              new_version="$major.$minor.$((patch + 1))"
              ;;
          esac
          echo "New Version: $new_version"

      # - name: Update pyproject.toml and __init__.py
      #   run: |
      #     new_version=$(<latest_tag.txt)
      #     sed -i "s/version = .*/version = \"$new_version\"/" pyproject.toml
      #     sed -i "s/__version__ = .*/__version__ = \"$new_version\"/" Src/ahd_data_piplines/__init__.py

      # - name: Commit changes
      #   run: |
      #     git add pyproject.toml Src/ahd_data_piplines/__init__.py
      #     git commit -m "Update version to $(<latest_tag.txt)"

      # - name: Tag and push changes
      #   run: |
      #     new_version=$(<latest_tag.txt)
      #     git tag -a "v$new_version" -m "Version $new_version"
      #     git push origin HEAD --tags
