name: Update Version

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      # Get latest Tag 
      - name: Find Latest Tag for ontargetcomputing/ahd-data-pipelines
        uses: tdemin/find-latest-tag@v1
        with:
          repo: https://github.com/ontargetcomputing/ahd-data-pipelines.git
        id: ahd_data_pipelines_tag
      - name: Print Latest Tag for ontargetcomputing/ahd-data-pipelines
        run: echo "Latest tag for ontargetcomputing/ahd-data-pipelines is ${{ steps.ahd_data_pipelines_tag.outputs.tag }}"

      # Get version label 
      - name: Extract version labels
        id: extract_labels
        run: |
          PR_LABELS=$(jq --raw-output '.pull_request.labels[].name' "$GITHUB_EVENT_PATH" || echo "")
          
          MINOR_LABEL=""
          MAJOR_LABEL=""
          PATCH_LABEL=""

          if [[ ! -z "$PR_LABELS" ]]; then
            MINOR_LABEL=$(echo "$PR_LABELS" | grep -i 'minor' || echo "")
            MAJOR_LABEL=$(echo "$PR_LABELS" | grep -i 'major' || echo "")
            PATCH_LABEL=$(echo "$PR_LABELS" | grep -i 'patch' || echo "")
          fi
          
          echo "::set-output name=minor_label::$MINOR_LABEL"
          echo "::set-output name=major_label::$MAJOR_LABEL"
          echo "::set-output name=patch_label::$PATCH_LABEL"

      - name: Display version labels
        run: |
          echo "Minor Label: ${{ steps.extract_labels.outputs.minor_label }}"
          echo "Major Label: ${{ steps.extract_labels.outputs.major_label }}"
          echo "Patch Label: ${{ steps.extract_labels.outputs.patch_label }}"

      # Make sure two labels don't exist
      - name: Check for multiple version labels
        run: |
          if [[ ! -z "${{ steps.extract_labels.outputs.minor_label }}" && \
                ! -z "${{ steps.extract_labels.outputs.major_label }}" || \
                ! -z "${{ steps.extract_labels.outputs.minor_label }}" && \
                ! -z "${{ steps.extract_labels.outputs.patch_label }}" || \
                ! -z "${{ steps.extract_labels.outputs.major_label }}" && \
                ! -z "${{ steps.extract_labels.outputs.patch_label }}" ]]; then
            echo "Error: More than one of the version labels (minor, major, patch) exist. Exiting..."
            exit 1
          fi

          OLD_VERSION="${{ steps.ahd_data_pipelines_tag.outputs.tag }}"
          IFS='.' read -ra VERSION_PARTS <<< "$OLD_VERSION"

          if [[ $MAJOR -eq 1 ]]; then
            NEW_VERSION="${VERSION_PARTS[0]}.0.0"
          elif [[ $MINOR -eq 1 ]]; then
            NEW_VERSION="${VERSION_PARTS[0]}.$((${VERSION_PARTS[1]} + 1)).0"
          elif [[ $PATCH -eq 1 ]]; then
            NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$((${VERSION_PARTS[2]} + 1))"
          else
            echo "No version label found. Exiting..."
            exit 1
          fi

          echo "::set-output name=new_version::$NEW_VERSION"