name: bump and tag branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - id: new_tag_version
    - name: Bump version and push tag
      uses: Instrument/github-tag-action@v1.0
      env:
        BRANCH: master
        BUMP: major