name: Update Version

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Find Latest Tag for ontargetcomputing/ahd-data-pipelines
        uses: tdemin/find-latest-tag@v1
        with:
          repo: https://github.com/ontargetcomputing/ahd-data-pipelines.git
        id: ahd_data_pipelines_tag
      - name: Print Latest Tag for ontargetcomputing/ahd-data-pipelines
        run: echo "Latest tag for ontargetcomputing/ahd-data-pipelines is ${{ steps.ahd_data_pipelines_tag.outputs.tag }}"
