name: Validate DEV deployment config

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      # - name: Install python dependencies
      #   run: |
      #     # python -m pip install --upgrade pip
      #     # pip install jinja2
      #     # pip install argparse
      #     # pip install pyyaml
      # - name: Install Poetry
      #   run: |
      #     echo "Install Poetry"
      #     curl -sSL https://install.python-poetry.org | python3 -
      # - name: Install libkrb5
      #   run: |
      #     echo "Install libkrb5"
      #     sudo apt-get update
      #     sudo apt-get install -y libkrb5-dev
      # - name: Install dependencies
      #   run: |
      #     echo "Install dependencies"
      #     poetry install
      # - name: Install databricks
      #   run: |
      #     echo "Install databricks"
      #     curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      # - name: Running Validate on dev
      #   run: |
      #     echo "Validate the dev configuration"
      #     make validate ENV=dev
      - name: Running Validate on dev
        run: |
          pwd
      - name: Running Validate on dev
        run: |
          touch /home/runner/.databrickscfg
          ls -al /home/runner 


