name: Update Version

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}

      - name: Determine Semantic Version Label
        id: determine_label
        run: |
          latest_tag=$(<latest_tag.txt)
          current_version=$(echo $latest_tag | cut -d 'v' -f 2)
          IFS='.' read -r major minor patch <<< "$current_version"
          if [ $major -eq 0 ]; then
            label="major"
          elif [ $minor -eq 0 ]; then
            label="minor"
          else
            label="patch"
          fi
          echo "Label: $label"

      - name: Increase version number
        id: increase_version
        run: |
          latest_tag=$(<latest_tag.txt)
          current_version=$(echo $latest_tag | cut -d 'v' -f 2)
          IFS='.' read -r major minor patch <<< "$current_version"
          case $label in
            major)
              new_version="$((major + 1)).0.0"
              ;;
            minor)
              new_version="$major.$((minor + 1)).0"
              ;;
            patch)
              new_version="$major.$minor.$((patch + 1))"
              ;;
          esac
          echo "New Version: $new_version"

      # - name: Update pyproject.toml and __init__.py
      #   run: |
      #     new_version=$(<latest_tag.txt)
      #     sed -i "s/version = .*/version = \"$new_version\"/" pyproject.toml
      #     sed -i "s/__version__ = .*/__version__ = \"$new_version\"/" Src/ahd_data_piplines/__init__.py

      # - name: Commit changes
      #   run: |
      #     git add pyproject.toml Src/ahd_data_piplines/__init__.py
      #     git commit -m "Update version to $(<latest_tag.txt)"

      # - name: Tag and push changes
      #   run: |
      #     new_version=$(<latest_tag.txt)
      #     git tag -a "v$new_version" -m "Version $new_version"
      #     git push origin HEAD --tags
