name: bump and tag branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Bump version and push tag
      id: new_version
      uses: Instrument/github-tag-action@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: main
        BUMP: major